name: 🐞 Bug Report
description: File a bug report for mechanics, electronics and/or related documentation.
title: "[Bug]: [Assembly/Part] - [Title description]"
labels: ["report-bug", "team-proto"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏🏻

  - type: dropdown
    id: domain
    attributes:
      label: Bug domain
      options:
        - Mechanincs
        - Electronics (e.g. boards o wiring)
        - Documentation
    validations:
      required: true

  - type: textarea
    id: comp-id
    attributes:
      label: Component identification
      description: Fill in the fowllowing table in order to identifiy the components that need attention.
      value: |
        |            | Alias | Code  | Revision | Description |
        |:---------  | :---: | :---: | :------: | :--------: |
        | Assembly:  |       |       |          |            |
        | Component: |       |       |          |            |
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Corrective actions
      description: Please, if you have any corrective actions to propose, feel free to add them below.
      placeholder: |
        - [ ] Insert here the *Corrective action n.1*
        - [ ] Insert here the *Corrective action n.2*
        - [ ] ...
