name: ⚙️ Task
description: Template to create a new task
labels: team-proto
body:
- type: textarea
  attributes:
    label: Task description
    placeholder: |
      Write here a meeaningful description of the task
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ```[tasklist]
      ### Tasks
        - [x] tendon replaced
        - [ ] joint tested successfully
      ```
