name: ⚙️ Task
description: Template to create a new task
labels: team-proto
body:
- type: textarea
  attributes:
    label: Task description
    placeholder: |
      Write here a meeaningful description of the task
  validations:
    required: true
- type: textarea
    attributes:
      label: Definition of Done
      placeholder: |
        ```[tasklist]
        - [ ] task 1
        - [ ] task 2
        ```
