name: 📦 Warehouse
description: Ticket for warehouse material
assignees: Miche19
title: WAREHOUSE - [Insert here a short title description]
labels: warehouse


body:
- type: input
  attributes:
    label: Applicant
    description: "Insert here the name of the applicant and his/her Github username"
    placeholder: "Name Surname, @github-username"
  validations:
    required: true

- type: input
  attributes:
    label: Applicant's Supervisor
    description: "Insert here the name of the applicant's supervisor and his/her Github username"
    placeholder: "Name Surname, @github-username"
  validations:
    required: true

- type: input
  attributes:
    label: Desired Complete Date
    placeholder: "Day/Month/Year"
  validations:
    required: true


- type: textarea
  id: details
  attributes:
    label: Request description
    placeholder: |
      Example:
      
      As per https://github.com/icub-tech-iit/task-force-miscellanea/issues/62, @DanielePucci's group has asked to equip iCub 3 with Bluetooth functionalities.
  validations:
    required: true


- type: textarea
  id: material
  attributes:
    label: Material item list
    description: "IIT-CODE is the part number in Wingst (http://wingst.icub.iit.local)"
    value: |
      | Item Name / IIT-CODE | Quantity | Description |
      |:--------------------:|:--------:|:------------|
      |  |  |  |
      |  |  |  |
  validations:
    required: true

- type: dropdown
  attributes:
    label: Material already retrieved?
    options:
      - "Yes"
      - "No"
    default: 1
  validations:
    required: true

- type: checkboxes
  id: cdc
  attributes:
    label: Insert the Cost Center (aka CDC)
    description: Select here the cost center where you have to allocate the cost of the material for your request.
    options:
      - label: WINGST ID 2246 - Lorenzo Natale (3C021 I913999900)
      - label: WINGST ID 2251 - Daniele Pucci (3C300 I913999900)
      - label: WINGST ID 2250 - Chiara Bartolozzi (3C201 I913999900)
      - label: WINGST ID 1748 - iCubTech (3C031 I913999900)
      - label: Other (You can find a short list of cost centers in [cdc-list](https://github.com/icub-tech-iit/tickets/blob/master/cdc.md), and a complete list in [wingst](wingst.icub.iit.local))
  validations:
    required: true

- type: input
  attributes:
    label: Other CDC (only if you checked "Other" in the previous section)
    placeholder: "WINGST ID XXXX - Facility Name"


- type: markdown
  attributes:
    value: |
      ### ⚠️ Read carefully the following instructions before submitting the ticket ⚠️

      - Add the label of your Research Line (for `iCub-Tech` member insert team name as well)
      - Use the label `priority-urgent` (🔴) only for urgent items (max 5 times per years for RL)
