name: 🤖 Test Robot 
description: Template to create a report for a robot test

body:
- type: dropdown
  id: robot
  attributes:
    label: Robot Name 🤖
    description: Please select the name of the robot to test.
    options:
      - "ergoCub 1.0 S/N:000"
      - "ergoCub 1.1 S/N:001"
      - "ergoCub 1.1 S/N:002"
      - "iCubAberystwyth01 S/N:018"
      - "iCubAnkara01 S/N:12"
      - "iCubBarcelona01 S/N:013"
      - "iCubBielefeld01 S/N:006"
      - "iCubBielefeld03 S/N:019"
      - "iCubChemnitz01 S/N:042"
      - "iCubDarmstadt01 S/N:025"
      - "iCubEdinburgh01 S/N:034"
      - "iCubErzelli01 S/N:032"
      - "iCubErzelli02 S/N:036"
      - "iCubFrankfurt01 S/N:019H"
      - "iCubGenova01 S/N:000"
      - "iCubGenova02 S/N:001"
      - "iCubGenova03 S/N:020"
      - "iCubGenova04 (iRonCub1) S/N:031"
      - "iCubGenova07 S/N:040"
      - "iCubGenova08 S/N:043"
      - "iCubGenova09 (iRonCub3) S/N:000"
      - "iCubGenova10 S/N:046"
      - "iCubGenova11 S/N:050"
      - "iCubGrenoble01 S/N:023"
      - "iCubHamburg01 S/N:027H"
      - "iCubHeidelberg01 S/N:029"
      - "iCubHertfordshire01 S/N:009"
      - "iCubHongKong01 S/N:041"
      - "iCubLausanne01 S/N:005"
      - "iCubLausanne02 S/N:033"
      - "iCubLisboa01 S/N:004"
      - "iCubLondon01 S/N:003"
      - "iCubLugano01 S/N:017"
      - "iCubLyon01 S/N:010"
      - "iCubManchester01 S/N:011"
      - "iCubMoscow01 S/N:038"
      - "iCubMunich01 S/N:008"
      - "iCubNancy01 S/N:021"
      - "iCubNottingham01 S/N:027"
      - "iCubTokyo01 S/N:022"
      - "iCubParis01 S/N:002"
      - "iCubParis02 S/N:024"
      - "iCubPisa01 S/N:037"
      - "iCubPlymouth01 S/N:007"
      - "iCubPrague01 S/N:047"
      - "iCubRome02 S/N:016"
      - "iCubSeoul01 S/N:026"
      - "iCubShanghai01 S/N:049"
      - "iCubSheffield01 S/N:028"
      - "iCubShenzhen01 S/N:039"
      - "iCubSingapore01 S/N:035"
      - "iCubTwente01 S/N:030"
      - "iCubUrbana01 S/N:015"
      - "iCubValparaiso01 S/N:048"
      - "iCubWaterloo01 S/N:044"
      - "iCubZagreb01 S/N:045"
      - "R1 S/N:000"
      - "R1 S/N:001"
      - "R1 S/N:002"
      - "R1 S/N:003"
  validations:
    required: true
- type: dropdown
  id: parts
  attributes:
    label: Parts 🦾
    multiple: true
    description: Please select one or more parts to test.
    options:
      - "Whole robot"
      - "Upper body"
      - "Lower body"
      - "Head"
      - "Left arm"
      - "Right arm"
      - "Left leg"
      - "Right leg"
  validations:
   required: true
- type: dropdown
  id: reason
  attributes:
    label: Test reason 📄
    description: Please select the reason of the test.
    options:
      - "Maintenance"
      - "Production"
      - "Other"
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other information about the test here.
    placeholder: |
      We are required to test the robot before shipping it to the customer.

- type: textarea
  attributes:
    label: Definition of Done divided by robot's part
    description: Before submitting, remove the part not involved in the robot's test
    value: |
        ### Preliminary checks / tests
        
        - [ ] General visual inspection
        - [ ] Test power on (both `head` and `motors`)
        - [ ] Test the discovery of the boards using `Firmwareupdater`
        - [ ] Update the firmware of all the boards
        - [ ] Test the joints encoders reading

        ### Specific tests for upper body

        - [ ] Head calibration
        - [ ] Arms calibration
        - [ ] Test joints motor moving

        ### Specific tests for Lower body

        - [ ] Legs calibration
        - [ ] Test joints motors moving

        ### Final tests before delivery

        - [ ] Test the cameras
        - [ ] Test the microphones & speakers
        - [ ] Test the skin
        - [ ] Test the encoders and joints limits
        - [ ] Test the face expressions
        - [ ] Test the yoga demo
        - [ ] Test force control
        - [ ] Red Ball demo
        - [ ] Clean up the robot folder (all the files created to calibrate the sub-assembly)
        - [ ] Make a PR in [robots-configuration](https://github.com/robotology/robots-configuration)
        - [ ] Delete from the head the older `robotology-superbuild`
        - [ ] Clone a new `robotology-superbuild` in the head from the lastest distro
        - [ ] Test the setup from the laptop with `yarpmanager` (all the functions)