name: ✈️ Travel Report
description: Template to create a new travel report 
labels: team-proto
body:
- type: dropdown
  id: robot
  attributes:
    label: Robot Name 🤖
    description: Please select the name of the robot involved in the event.
    options:
      - "ergoCub 1.0 S/N:000"
      - "ergoCub 1.1 S/N:001"
      - "ergoCub 1.1 S/N:002"
      - "iCubGenova04 (iRonCub1) S/N:031"
      - "iCubGenova09 (iRonCub3) S/N:000"
    multiple: true
  validations:
    required: true


- type: textarea
  attributes:
    label: Report Day 1
    description: This issue will track all materials used, interventions made, and issues encountered during the event.
    value: |
      - Material inserted in the toolboxes:
        - n/a

      - Material removed from the toolboxes:
        - ...

      - Activities done (maintenance interventions): 
        - ...

      ### IIT Codes of material used / initially missing

      | IIT-CODE | Revision | Quantity | Description | [ Serial Number (S/N) ] |
      |:--------:|:--------:|:--------:|:-----------:|:------------------------|
      |  |  |  |  |  |
      |  |  |  |  |  |

      >**Note:**
      >- ...

      ---
  validations:
    required: true



- type: textarea
  attributes:
    label: Definition of Done
    placeholder: |
      - [ ] All the activities have been reported
  validations:
    requiered: true